name: Scott Pretty
favicon: null
layout_spectrum: 1
typography_spectrum: 0.20673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#23526e'
    - '#100d06'
    - '#d7b48e'
    - '#99784f'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
