name: Scott Pretty
favicon: null
layout_spectrum: 0.60925
typography_spectrum: 0.20673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00344c'
    - '#00529b'
    - '#000000'
    - '#bed9ee'
    - '#276197'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
